version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=platform
    ports:
      - "5432:5432"
  keycloak:
    image: 'quay.io/keycloak/keycloak:20.0.1'
    restart: always
    ports:
      - '3000:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
