--CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- create table customer
create table ct.t_ct
(
    id_internal BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_external uuid not null DEFAULT uuid_generate_v4 (),
    first_name varchar(100),
    last_name varchar(100),
    birth_date date,
    created_at date default current_date,
    updated_at timestamp default current_timestamp
);
-- descrption columns customers
comment on table  ct.t_ct is 'table customers';
comment on column ct.t_ct.first_name  is  'the first_name customer';
comment on column ct.t_ct.last_name   is  'the fisrt name customer';
comment on column ct.t_ct.id_internal is  'the customer id long';
comment on column ct.t_ct.id_external is  'the customer uuid';
comment on column ct.t_ct.birth_date  is  'the customer birth date ';
-- define key words
alter table ct.t_ct add constraint pk_ct primary key (id_internal);

-- define unique key
alter table ct.t_ct add constraint key_ct UNIQUE (first_name,last_name,birth_date);
-- define index
create index idx_ct_id_internal ON ct.t_ct(id_internal);
create index idx_ct_id_ixternal ON ct.t_ct(id_external);

-- create table document cpf lgpd
create table ct.t_dc_cpf_lgpd (
                                  id_internal BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  id_external uuid default uuid_generate_v4(),
                                  id_t_ct bigint,
                                  is_authorization boolean not null default true,
                                  document varchar(11),
                                  created_at date default current_date,
                                  updated_at timestamp default current_timestamp
);

-- define keys document cpf lgpd
alter table ct.t_dc_cpf_lgpd add constraint pk_dc_cpf_lgpd primary key (id_internal);
-- add foreign keys document cpf lgpd
alter table ct.t_dc_cpf_lgpd  add constraint fk_dc_cpf_lgpd foreign key (id_t_ct) references ct.t_ct(id_internal);
-- define index document cpf lgpd
create index idx_t_dc_cpf_lgpd_id_internal  ON ct.t_dc_cpf_lgpd(id_internal);
create index idx_t_dc_cpf_lgpd_id_external  ON ct.t_dc_cpf_lgpd(id_external);
create index idx_t_dc_cpf_lgpd_id_table     ON ct.t_dc_cpf_lgpd(id_t_ct);
create index idx_t_dc_cpf_lgpd_document     ON ct.t_dc_cpf_lgpd(document);

-- create table document cpf lgpd
create table ct.t_dc_cnpj_lgpd (
                                   id_internal BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   id_external uuid default uuid_generate_v4(),
                                   id_t_ct bigint,
                                   is_authorization boolean not null default true,
                                   document varchar(11),
                                   created_at date default current_date,
                                   updated_at timestamp default current_timestamp
);

-- define keys document cpf lgpd
alter table ct.t_dc_cnpj_lgpd add constraint pk_dc_cnpj_lgpd primary key (id_internal);
-- add foreign keys document cpf lgpd
alter table ct.t_dc_cnpj_lgpd  add constraint fk_dc_cnpj_lgpd foreign key (id_t_ct) references ct.t_ct(id_internal);
-- define index document cpf lgpd
create index idx_t_dc_cnpj_lgpd_id_internal  ON ct.t_dc_cnpj_lgpd(id_internal);
create index idx_t_dc_cnpj_lgpd_id_external  ON ct.t_dc_cnpj_lgpd(id_external);
create index idx_t_dc_cnpj_lgpd_document     ON ct.t_dc_cnpj_lgpd(document);



--  create table address
create table ct.t_as(
                        id_internal BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        id_external uuid default uuid_generate_v4(),
                        id_t_ct bigint,
                        created_at date default current_date,
                        updated_at timestamp default current_timestamp,
                        state varchar(10),
                        city_name varchar(100),
                        neighborhood varchar(100),
                        cep varchar(100),
                        number int,
                        address_name varchar(1000),
                        complement varchar(100)
);
-- define key address
alter table ct.t_as add constraint pk_t_as primary key (id_internal);
-- add foreign keys address
alter table ct.t_as  add constraint fk_t_as foreign key (id_t_ct) references ct.t_ct(id_internal);
-- define index address
create index idx_t_as_id_internal  ON ct.t_as(id_internal);
create index idx_t_as_id_external  ON ct.t_as(id_external);


--  create table account
create table ct.t_ac(
                        id_internal BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        id_external uuid default uuid_generate_v4(),
                        id_t_ct bigint,
                        created_at date default current_date,
                        updated_at timestamp default current_timestamp,
                        email varchar(100),
                        user_name varchar(100)
);
-- define key account
alter table ct.t_ac add constraint pk_t_ac primary key (id_internal);
-- add foreign keys account
alter table ct.t_ac  add constraint fk_t_ac foreign key (id_t_ct) references ct.t_ct(id_internal);

-- define unique key
alter table ct.t_ac add constraint key_ac UNIQUE (email,user_name);
-- define index account
create index idx_t_ac_id_internal  ON ct.t_ac(id_internal);
create index idx_t_ac_id_external  ON ct.t_ac(id_external);

--  create table passwd
create table ps.t_key(
                         id_internal BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         id_external uuid default uuid_generate_v4(),
                         id_t_ac bigint,
                         created_at date default current_date,
                         updated_at timestamp default current_timestamp ,
                         key_secret varchar(1000)
);

-- define key account
alter table ps.t_key add constraint pk_t_key_secret primary key (id_internal);
-- add foreign keys account
alter table ps.t_key  add constraint fk_t_key_secret foreign key (id_t_ac) references ct.t_ac(id_internal);
-- define index account
create index idx_t_key_id_internal   ON ps.t_key(id_internal);
create index idx_t_key_external      ON ps.t_key(id_external);
create index idx_t_key_table         ON ps.t_key(id_t_ac);
create index idx_t_key_key_secret    ON ps.t_key(key_secret);

--  create table passwd
create table ps.t_passwd(
                            id_internal BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            id_external uuid default uuid_generate_v4(),
                            id_t_ac bigint,
                            created_at date default current_date,
                            updated_at timestamp default current_timestamp,
                            key_crypt varchar(1000)
);

-- define key account
alter table ps.t_passwd add constraint pk_t_passwd primary key (id_internal);
-- add foreign keys account
alter table ps.t_passwd  add constraint fk_t_passwd foreign key (id_t_ac) references ct.t_ac(id_internal);
-- define index account
create index idx_t_passwd_id_internal   ON ps.t_passwd(id_internal);
create index idx_t_passwd_external      ON ps.t_passwd(id_external);
